# Generated by Django 4.2.7 on 2026-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Mouse', 'Mouse'), ('Keyboard', 'Keyboard'), ('Monitor', 'Monitor'), ('Projector', 'Projector'), ('Printer', 'Printer'), ('Scanner', 'Scanner'), ('UPS', 'UPS'), ('Other', 'Other')], max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working'), ('Damaged', 'Damaged'), ('Old', 'Old')], default='Working', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Accessories',
                'db_table': 'accessories',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Access Point', 'Access Point'), ('Switch', 'Switch'), ('Router', 'Router'), ('Modem', 'Modem'), ('Firewall', 'Firewall'), ('Other', 'Other')], max_length=100)),
                ('brand', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='e.g., 192.168.1.1', null=True)),
                ('location', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working'), ('Damaged', 'Damaged'), ('Old', 'Old')], default='Working', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'network_devices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(help_text='e.g., Dell, HP, Lenovo', max_length=100)),
                ('ram', models.CharField(help_text='e.g., 8GB, 16GB', max_length=50)),
                ('hdd', models.CharField(help_text='e.g., 500GB HDD, 256GB SSD', max_length=50)),
                ('operating_system', models.CharField(help_text='e.g., Windows 10, Ubuntu 22', max_length=100)),
                ('registration_year', models.IntegerField(help_text='Year this PC was registered')),
                ('location', models.CharField(choices=[('Lab', 'Lab'), ('Office', 'Office')], default='Office', max_length=20)),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working'), ('Damaged', 'Damaged'), ('Old', 'Old')], default='Working', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'pcs',
                'ordering': ['-created_at'],
            },
        ),
    ]
