# Generated by Django 4.2.7 on 2026-03-10 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pc',
            name='technician_assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_pcs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='technician_assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_network_devices', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='accessory',
            name='technician_assigned',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_accessories', to=settings.AUTH_USER_MODEL),
        ),
    ]
