# Generated by Django 4.2.7 on 2026-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telephone', models.CharField(max_length=20)),
                ('unit', models.CharField(help_text='Department or Unit name', max_length=100)),
                ('request_type', models.CharField(choices=[('Internet cable installation', 'Internet cable installation'), ('OS repair', 'OS repair'), ('Antivirus installation', 'Antivirus installation'), ('Hardware repair', 'Hardware repair'), ('Software installation', 'Software installation'), ('Network troubleshooting', 'Network troubleshooting'), ('Data recovery', 'Data recovery'), ('Other ICT services', 'Other ICT services')], max_length=100)),
                ('description', models.TextField(help_text='Describe the issue in detail')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Technician Assigned', 'Technician Assigned'), ('Fixed', 'Fixed'), ('Not Fixed', 'Not Fixed')], default='Pending', max_length=30)),
            ],
            options={
                'db_table': 'requests',
                'ordering': ['-date'],
            },
        ),
    ]
