# Generated by Django 4.2.7 on 2026-03-10 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='assigned_technician',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'Technician'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_requests', to=settings.AUTH_USER_MODEL),
        ),
    ]
