# Generated by Django 4.2.7 on 2026-03-10 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_type', models.CharField(choices=[('PC', 'PC'), ('Accessory', 'Accessory'), ('NetworkDevice', 'Network Device')], max_length=20)),
                ('device_id', models.IntegerField(help_text='The ID of the PC, Accessory, or Network Device')),
                ('status', models.CharField(choices=[('Working', 'Working'), ('Not Working', 'Not Working'), ('Damaged', 'Damaged'), ('Old', 'Old'), ('Repaired', 'Repaired'), ('Replaced', 'Replaced')], max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('report_date', models.DateField(auto_now_add=True)),
                ('description', models.TextField(help_text='Describe what was done or what the problem is')),
            ],
            options={
                'db_table': 'reports',
                'ordering': ['-report_date'],
            },
        ),
    ]
