# Generated by Django 4.2.9 on 2026-03-20 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_passwordreset'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passwordreset',
            name='token',
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='passwordreset',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
